# Generated by Django 2.1.7 on 2019-03-28 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('user', models.CharField(blank=True, max_length=28, null=True)),
                ('referal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=28, null=True)),
                ('ip', models.CharField(blank=True, max_length=28, null=True)),
                ('country', models.CharField(blank=True, max_length=28, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSiteVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=28, null=True)),
                ('spent_full_time', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='sitevisits.Referal')),
            ],
        ),
    ]
