# Generated by Django 2.1.7 on 2019-03-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisits', '0002_auto_20190328_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersitevisits',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='sitevisits.Referal'),
            preserve_default=False,
        ),
    ]
